export enum UserErrCodes {
  'ERR_USER_NON_EXIST' = 'ERR_USER_NON_EXIST',
  'ERR_INCORRECT_CREDS' = 'ERR_INCORRECT_CREDS',
  'ERR_USERNAME_ALREADY_EXISTS' = 'ERR_USERNAME_ALREADY_EXISTS',
  'ERR_EMAIL_ALREADY_EXISTS' = 'ERR_EMAIL_ALREADY_EXISTS'
}
